### ISSUE TITLE
Tree Mortality Roadmap

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest_Model#15]
Here is a general guidance issue for the bounds of the tree mortality project.

- [X] Two class deep learning model that predicts on DeepForest crops
- [ ] Add Hyperspectral arm
- [ ] 2x rounds of hard mining
- [ ] Drop sites like SRER, MOAB
- [ ] Holdout validation dataset
- [ ] Learning rate monitor
- [ ] Profile predict field trees
- [ ] field trees as eval metric on comet
- [ ] decent docs and readme so that the project can be picked up after species classification.
